### ISSUE TITLE
Input file format for anpan

### ISSUE THREAD

**Issue by Nick243** [biobakery/anpan#1]
Hi Andrew,

I attended your talk yesterday and am looking forward to familiarizing myself with your anpan program and to reading the forthcoming paper. 

I installed the program from github, but am unsure of what the file format structure needs to look like to run anpan_batch. 

**Is the bug_dir call expecting a file that contains a single stratified (i.e., contribution of each species as separate row) UniRef90 gene family table where the contribution of gene families has been filtered to a single species?**  

**Is the meta_file call expecting a single folder that contains a .tsv file of metadata where the columns are variables?**  

I tried to follow your example of using the Gupta data in the curatedMetagenomicData package with the code below, but got an error:
*“Error: Can't subset columns that don't exist.  
Column `bug_name` doesn't exist.”* 

Below is a reproducible example.  

Thank you in advance for any assistance in this matter. 

Nick

```

#Load libraries
library(curatedMetagenomicData); packageVersion("curatedMetagenomicData")     #version: 3.0.10
library(tidyverse); packageVersion("tidyverse")                                  #version: 1.3.1 
library(anpan); packageVersion("anpan")                                            #version: 0.1.0

#Pull down example data (Gupta 2019)
meta_df <- curatedMetagenomicData::sampleMetadata

mydata <- meta_df %>%
  select(study_name, sample_id, subject_id, study_condition, body_site, age, gender, BMI) %>%
  filter(study_name == "GuptaA_2019") 

keep_id <- mydata$sample_id

my_se <- sampleMetadata %>%
  dplyr::filter(sample_id %in% keep_id) %>%
  curatedMetagenomicData::returnSamples("gene_families")


#Filter gene family table to contributions from E.coli
gf_df <- as.data.frame(as.matrix(assay(my_se)))

ecoli_df <- gf_df %>%
  rownames_to_column(var = "UniRef90_gene_family") %>%
  filter(grepl("s__Escherichia_coli", UniRef90_gene_family)) %>%
  mutate(bug_name = "E.coli")


#Generate input files
dir.create("/users/olljt2/desktop/gf_data")
write_tsv(ecoli_df, "/users/olljt2/desktop/gf_data/ecoli_df.tsv")

dir.create("/users/olljt2/desktop/meta_data")
write_tsv(mydata, "/users/olljt2/desktop/meta_data/mydata.tsv")


#Fit anpan_batch
res <- anpan_batch(
  bug_dir = "/users/olljt2/desktop/gf_data",
  meta_file = "/users/olljt2/desktop/meta_data",
  out_dir = "/users/olljt2/desktop/anpan",
  model_type = "horseshoe",
  covariates = c("age", "gender"),
  outcome = "study_condition",
)

```

**Comment by andrewGhazi** [comment]
> Is the bug_dir call expecting a file that contains a single stratified (i.e., contribution of each species as separate row) UniRef90 gene family table where the contribution of gene families has been filtered to a single species?

bug_dir should be a string giving a directory that has multiple e.g. uniref90 gene family files, one for each bug. But since you're only looking at a single bug you should use `anpan()` instead of `anpan_batch()`.

> Is the meta_file call expecting a single folder that contains a .tsv file of metadata where the columns are variables?

meta_file should be a path to a tsv file (not a directory). So in your example I think you'd need to set `meta_file = "/users/olljt2/desktop/meta_data/mydata.tsv"`

I think you shouldn't need to add the bug_name column manually, it _should_ be able to figure it out automatically.

Be warned that _E. coli_ has an enormous number of unirefs associated with it which can trip up the adaptive filtering. When there's over 50k genes it trips a change in behavior that makes anpan take the log of the x-axis before running kmeans. Make sure the filtering diagnostic plot looks okay before interpreting your results.

**Comment by Nick243** [comment]
Thank so much for the quick reply and warning re *E.coli*.!   

I was able to get the anpan function running with your suggested modifications.
